language: php

php:
  - 7.1
  - 7.2

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script: git reset --hard HEAD

script:
  - scripts/phpcs.sh
  - scripts/phpunit.sh
