language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script: git reset --hard HEAD

script:
  - scripts/phpcs.sh
