tabs:
    fields:
        contact_email_de:
            label: 'liip.repaircafe::lang.theme.fields.contact_email_de'
            span: full
            type: text
            default: 'repaircafe@konsumentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        contact_email_fr:
            label: 'liip.repaircafe::lang.theme.fields.contact_email_fr'
            span: full
            type: text
            default: 'repaircafe@konsumentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        contact_email_it:
            label: 'liip.repaircafe::lang.theme.fields.contact_email_it'
            span: full
            type: text
            default: 'repaircafe@konsmentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        logo_url_de:
            label: 'liip.repaircafe::lang.theme.fields.logo_url_de'
            span: full
            type: text
            default: 'https://www.konsumentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        logo_url_fr:
            label: 'liip.repaircafe::lang.theme.fields.logo_url_fr'
            span: full
            type: text
            default: 'https://www.konsumentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        logo_url_it:
            label: 'liip.repaircafe::lang.theme.fields.logo_url_it'
            span: full
            type: text
            default: 'https://www.konsumentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        social_facebook_de:
            label: 'liip.repaircafe::lang.theme.fields.social_facebook_de'
            span: full
            type: text
            default: 'https://www.facebook.com/stiftungfuerkonsumentenschutz/'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        social_facebook_fr:
            label: 'liip.repaircafe::lang.theme.fields.social_facebook_fr'
            span: full
            type: text
            default: 'https://www.facebook.com/stiftungfuerkonsumentenschutz/'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        social_facebook_it:
            label: 'liip.repaircafe::lang.theme.fields.social_facebook_it'
            span: full
            type: text
            default: 'https://www.facebook.com/stiftungfuerkonsumentenschutz/'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        social_twitter_de:
            label: 'liip.repaircafe::lang.theme.fields.social_twitter_de'
            span: full
            type: text
            default: 'https://twitter.com/KonsumSchutz'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        social_twitter_fr:
            label: 'liip.repaircafe::lang.theme.fields.social_twitter_fr'
            span: full
            type: text
            default: 'https://twitter.com/KonsumSchutz'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        social_twitter_it:
            label: 'liip.repaircafe::lang.theme.fields.social_twitter_it'
            span: full
            type: text
            default: 'https://twitter.com/KonsumSchutz'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        social_googleplus_de:
            label: 'liip.repaircafe::lang.theme.fields.social_googleplus_de'
            span: full
            type: text
            default: 'https://plus.google.com/+KonsumentenschutzCh'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        social_googleplus_fr:
            label: 'liip.repaircafe::lang.theme.fields.social_googleplus_fr'
            span: full
            type: text
            default: 'https://plus.google.com/+KonsumentenschutzCh'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        social_googleplus_it:
            label: 'liip.repaircafe::lang.theme.fields.social_googleplus_it'
            span: full
            type: text
            default: 'https://plus.google.com/+KonsumentenschutzCh'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        mailchimp_domain_de:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_domain_de'
            span: full
            type: text
            comment: 'liip.repaircafe::lang.theme.fields.comments.mailchimp_domain'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        mailchimp_domain_fr:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_domain_fr'
            span: full
            type: text
            comment: 'liip.repaircafe::lang.theme.fields.comments.mailchimp_domain'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        mailchimp_domain_it:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_domain_it'
            span: full
            type: text
            comment: 'liip.repaircafe::lang.theme.fields.comments.mailchimp_domain'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        mailchimp_user_id_de:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_user_id_de'
            span: left
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        mailchimp_user_id_fr:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_user_id_fr'
            span: left
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        mailchimp_user_id_it:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_user_id_it'
            span: left
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        mailchimp_list_id_de:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_list_id_de'
            span: right
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_de'
        mailchimp_list_id_fr:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_list_id_fr'
            span: right
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_fr'
        mailchimp_list_id_it:
            label: 'liip.repaircafe::lang.theme.fields.mailchimp_list_id_it'
            span: right
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.general_it'
        google_analytics_tracking_id:
            label: 'liip.repaircafe::lang.theme.fields.google_analytics_tracking_id'
            span: full
            type: text
            tab: 'liip.repaircafe::lang.theme.fields.tab.google_analytics'
        repair_cafe_default_image:
            label: 'liip.repaircafe::lang.theme.fields.repair_cafe_default_image'
            span: left
            type: mediafinder
            mode: image
            tab: 'liip.repaircafe::lang.theme.fields.tab.default_content'
        repair_cafe_default_logo:
            label: 'liip.repaircafe::lang.theme.fields.repair_cafe_default_logo'
            span: left
            type: mediafinder
            mode: image
            tab: 'liip.repaircafe::lang.theme.fields.tab.default_content'
