tabs:
    fields:
        contact_email:
            label: 'liip.repaircafe::lang.theme.fields.contact_email'
            span: full
            type: text
            default: 'repaircafe@konsumentenschutz.ch'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general'
        social_facebook:
            label: 'liip.repaircafe::lang.theme.fields.social_facebook'
            span: full
            type: text
            default: 'https://www.facebook.com/stiftungfuerkonsumentenschutz/'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general'
        social_twitter:
            label: 'liip.repaircafe::lang.theme.fields.social_twitter'
            span: full
            type: text
            default: 'https://twitter.com/KonsumSchutz'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general'
        social_googleplus:
            label: 'liip.repaircafe::lang.theme.fields.social_googleplus'
            span: full
            type: text
            default: 'https://plus.google.com/+KonsumentenschutzCh'
            tab: 'liip.repaircafe::lang.theme.fields.tab.general'
        repair_cafe_default_image:
            label: 'liip.repaircafe::lang.theme.fields.repair_cafe_default_image'
            span: left
            type: mediafinder
            mode: image
            tab: 'liip.repaircafe::lang.theme.fields.tab.default_content'
        repair_cafe_default_logo:
            label: 'liip.repaircafe::lang.theme.fields.repair_cafe_default_logo'
            span: left
            type: mediafinder
            mode: image
            tab: 'liip.repaircafe::lang.theme.fields.tab.default_content'
