de:
    contact.facebook: 'Facebook'
    contact.twitter: 'Twitter'
    eventsearch.category.label: 'Kategorie'
    eventsearch.searchterm.label: 'Suchbegriff'
    eventsearch.searchterm.placeholder: 'Suchbegriff...'
    eventsearch.submit.label: 'Jetzt suchen'
    cafes.title: 'Finde ein Repair Café'
    eventlist.additional_info_toggle: 'Zusätzliche Informationen auf-/zuklappen'
    eventlist.title: 'Zukünftige Events'
    eventlist.no_events_found: 'Keine zukünftigen Events gefunden'
    eventlist.cafe_detail_button: 'Mehr über dieses Repair Café'
    eventlist.open_external_map: 'Externen Kartendienst öffnen'
    homepage.title: ':repair_cafe_count Repair Café in der Schweiz|:repair_cafe_count Repair Cafés in der Schweiz'
    homepage.category_list.title: 'Was reparieren wir?'
    homepage.search.title: 'Finde ein Repair Café'
    homepage.news.show_more_btn: 'Alle Neuigkeiten'
    homepage.news.title: 'Aktuelles'
    newslist.lead: 'Lorem ipsum dolor sit amet, ad usu quaeque commune prodesset, id solet principes sit. Lorem interpretaris et nec. Nec ne possim invidunt repudiandae. Nam luptatum singulis ad, ut sit ullum molestie. Esse nibh qui ne, ei minim vivendum facilisis vis.'
    newslist.no_news_found: 'Momentan gibt es keine neuen Nachrichten'
    newslist.title: 'Aktuelles'
    page.404.content: 'Ups! Da ist etwas schief gelaufen.'
    page.404.title: 'Seite nicht gefunden'
    page.cafe.contact_link: 'Kontaktformular'
    page.cafe.contacts: 'Ansprechpersonen'
    page.cafe.facebook: 'Facebook'
    page.cafe.instagram: 'Instagram'
    page.cafe.twitter: 'Twitter'
    page.cafe.embed: 'Events in eigener Seite einbinden'
    page.cafe.embed.modal.title: 'Events in eigener Seite einbinden'
    page.cafe.embed.modal.close: 'Schliessen'
    site.footer.sks_logo: 'Konsumentenschutz Logo'
    site.header.service_area.title: 'Reparieren statt wegwerfen!'
    site.header.service_area.login: 'Login'
    site.header.main_navigation.toggler.label: 'Navigation auf-/zuklappen'
    site.header.repair_cafe_logo: 'Repair Café Logo'
    site.title: 'Repair Café'
    social_links.facebook: 'Konsumentenschutz auf Facebook'
    social_links.twitter: 'Konsumentenschutz auf Twitter'
    social_links.googleplus: 'Konsumentenschutz auf Google+'
