de:
    site.header.service_area.title: 'Reperatur-Bewegung Schweiz'
    site.header.service_area.login: 'Login'
    site.header.main_navigation.toggler.label: 'Navigation auf-/zuklappen'
    eventlist.title: 'Finde ein Repair Café'
    eventlist.search.searchterm.placeholder: 'Suchbegriff...'
    eventlist.search.searchterm.label: 'Suchbegriff'
    eventlist.search.category.label: 'Kategorie'
