de:
    contact.facebook: 'Facebook'
    contact.twitter: 'Twitter'
    eventlist.search.category.label: 'Kategorie'
    eventlist.search.searchterm.label: 'Suchbegriff'
    eventlist.search.searchterm.placeholder: 'Suchbegriff...'
    eventlist.title: 'Finde ein Repair Café'
    eventlist.no_events_found: 'Keine Events für die angegebenen Suchkriterien gefunden'
    eventlist.cafe_detail_button: 'Mehr über dieses Repair Café'
    eventlist.map.category_title: 'Kategorien'
    eventlist.map.date: 'Datum'
    eventlist.map.address: 'Ort'
    page.404.content: 'Ups! Da ist etwas schief gelaufen.'
    page.404.title: 'Seite nicht gefunden'
    page.cafe.address: 'Adresse'
    page.cafe.contact_link: 'Kontaktformular'
    page.cafe.contacts: 'Ansprechpersonen'
    page.cafe.external_links: 'Weitere Informationen'
    page.cafe.facebook: 'Facebook'
    page.cafe.instagram: 'Instagram'
    page.cafe.twitter: 'Twitter'
    page.cafe.website_link: 'Webseite'
    site.header.service_area.title: 'Reperatur-Bewegung Schweiz'
    site.header.service_area.login: 'Login'
    site.header.main_navigation.toggler.label: 'Navigation auf-/zuklappen'
