de:
    contact.facebook: 'Facebook'
    contact.twitter: 'Twitter'
    eventlist.search.category.label: 'Kategorie'
    eventlist.search.searchterm.label: 'Suchbegriff'
    eventlist.search.searchterm.placeholder: 'Suchbegriff...'
    eventlist.title: 'Finde ein Repair Café'
    page.cafe.address: 'Adresse'
    page.cafe.contact_link: 'Kontaktformular'
    page.cafe.contacts: 'Ansprechpersonen'
    page.cafe.external_links: 'Weitere Informationen'
    page.cafe.facebook: 'Facebook'
    page.cafe.instagram: 'Instagram'
    page.cafe.twitter: 'Twitter'
    page.cafe.website_link: 'Webseite'
    site.header.service_area.title: 'Reperatur-Bewegung Schweiz'
    site.header.service_area.login: 'Login'
    site.header.main_navigation.toggler.label: 'Navigation auf-/zuklappen'
