# This is a basic workflow to help you get started with Actions

name: Build & Deploy Stage

# Controls when the action will run.
on:
  # Triggers the workflow on push events to master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup composer cache
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
      - name: Install composer dependencies
        run: composer install
      - name: Lint source files
        run: scripts/phpcs.sh

  # This workflow contains a single job called "deploy"
  deploy:
    name: Build & Deploy

    needs: [ lint ]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Node 14
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup composer cache
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
      - name: Install composer dependencies
        run: composer install
      - name: Install npm dependencies
        run: npm i
      - name: Build assets
        run: npm run production
      - name: Copy source files to remote host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./*,!node_modules/"
          target: "/home/repairca/public_html/stage"
      - name: Run update scripts on remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            cd /home/repairca/public_html/stage
            php artisan october:up
            php artisan cache:clear
